from typing import Protocol


class ISyncEvent(Protocol):
    def set(self) -> None: ...
    def is_set(self) -> bool: ...
    def wait(self, timeout: float | None = None) -> bool: ...


class IAsyncEvent(Protocol):
    def set(self) -> None: ...
    def is_set(self) -> bool: ...
    async def wait(self) -> bool: ...


IEvent = ISyncEvent | IAsyncEvent
